### ISSUE TITLE
PROCESSINGS: Retrieve User By Credentials

### ISSUE THREAD

**Issue by ElbekDeveloper** [ElbekDeveloper/Tarteeb#154]
RetrieveUserByCredentials(string username, string password)

**Comment by GulchexrasGithub** [comment]
I will do this one

**Comment by ElbekDeveloper** [comment]
We will not use this, but let it stay as a reference and Add logic test

**Comment by ElbekDeveloper** [comment]
@Javlonbek-dev tugatib qoyasizmi bu ticketni?

**Comment by Javlonbek-dev** [comment]
> @Javlonbek-dev tugatib qoyasizmi bu ticketni?

Ha tugatib qo'yaman
