### ISSUE TITLE
FOUNDATIONS: Modify `Score`

### ISSUE THREAD

**Issue by GulchexrasGithub** [ElbekDeveloper/Tarteeb#234]

**Comment by sarvarbek-dev** [comment]
i will do this

**Comment by Xurshid-A-J** [comment]
@Xurshid-A-J
I will take it

**Comment by ElbekDeveloper** [comment]
@Jahongir1507 qiladilar. @Xurshid-A-J javob yozmaganingiz uchun qilmayapsiz deb o'yladik.
