### ISSUE TITLE
CONTROLLERS: GET All `Scores`

### ISSUE THREAD

**Issue by GulchexrasGithub** [ElbekDeveloper/Tarteeb#240]

**Comment by abbosbeck** [comment]
I took it

**Comment by GulchexrasGithub** [comment]
> I took it

Could you give us this issue?

**Comment by abbosbeck** [comment]
> > I took it
> 
> Could you give us this issue?

The task will start once the `RetrieveAllScores` method in the ScoresService has completed. @jasurbekyusuf informed me yesterday that your task is to `RetrieveAllScores`
